setup protractor configuration
Blesfia/protractor-workshop-2017 pull request #1
Opened 2017-10-03 02:58 UTC by Blesfia

2017-10-03 12:50 UTC, aperdomob requested changes

2017-10-03 12:50 UTC, aperdomob commented on test/spec.js
> +
eliminar los espacios en limpio de esta última línea

2017-10-03 13:58 UTC, jhenaoz submitted a review, later dismissed
EOF

2017-10-03 13:58 UTC, jhenaoz commented on test/spec.js
> +
una buena práctica para que esto no pase es usar editorconfig.
http://editorconfig.org/

2017-10-04 00:59 UTC, Blesfia commented on test/spec.js
> +
Listo :)

2017-10-04 02:03 UTC, aperdomob approved these changes

2017-10-04 02:34 UTC, merged