add files to improve locators
Blesfia/protractor-workshop-2017 pull request #15
Opened 2017-10-17 16:14 UTC by Blesfia

2017-10-17 17:07 UTC, aperdomob requested changes

2017-10-17 17:07 UTC, aperdomob commented on src/page/AddressStep.page.ts
> +    return $('.cart_navigation > button');
no entiendo porque cambias el # por .

2017-10-17 17:07 UTC, aperdomob commented on src/page/BankPayment.page.ts
> +    return $('.cart_navigation > button');
no entiendo porque cambias el # por .

2017-10-17 17:07 UTC, aperdomob commented on src/page/PaymentStep.page.ts
> +    return $('#HOOK_PAYMENT .bankwire');
creo que te funciona .bankwire

2017-10-17 17:07 UTC, aperdomob commented on src/page/ShippingStep.page.ts
> +    return $('.cart_navigation > button');
prefiero un id que un class, es decir, prefiero #form

2017-10-17 18:15 UTC, Blesfia commented on src/page/AddressStep.page.ts
> +    return $('.cart_navigation > button');
La idea es llegar al elemento en la menor cantidad de pasos, no es mas fácil llegar a el con dos pasos a usar 5?

2017-10-17 18:16 UTC, Blesfia commented on src/page/BankPayment.page.ts
> +    return $('.cart_navigation > button');
La idea es llegar al elemento en la menor cantidad de pasos, no es mas fácil llegar a el con dos pasos a usar 3?

2017-10-17 18:16 UTC, Blesfia commented on src/page/PaymentStep.page.ts
> +    return $('#HOOK_PAYMENT .bankwire');
Lo intente pero la prueba fallaba

2017-10-17 18:17 UTC, Blesfia commented on src/page/ShippingStep.page.ts
> +    return $('.cart_navigation > button');
Pero entonces, uno que debe preferir, los ids a class o el menor numero de pasos necesarios para localizar el elemento?

2017-10-17 21:45 UTC, aperdomob requested changes

2017-10-17 21:45 UTC, aperdomob commented on src/page/AddressStep.page.ts
> +    return $('.cart_navigation > button');
#center_column > button

2017-10-17 21:45 UTC, aperdomob commented on src/page/BankPayment.page.ts
> +    return $('.cart_navigation > button');
$('#cart_navigation span')

2017-10-17 21:45 UTC, aperdomob commented on src/page/AddressStep.page.ts
> +    return $('.cart_navigation > button');
$('[name="processAddress"]')

2017-10-17 21:45 UTC, aperdomob commented on src/page/PaymentStep.page.ts
> +    return $('#HOOK_PAYMENT .bankwire');
A mi me funciona bien

2017-10-17 21:45 UTC, aperdomob commented on src/page/ProductDetail.page.ts
> +    return $('#add_to_cart > button');
#add_to_cart

2017-10-17 21:45 UTC, aperdomob commented on src/page/ShippingStep.page.ts
> +    return $('.cart_navigation > button');
[name="processCarrier"]

2017-10-18 13:53 UTC, Blesfia commented on src/page/AddressStep.page.ts
> +    return $('.cart_navigation > button');
De acuerdo

2017-10-18 13:56 UTC, Blesfia commented on src/page/AddressStep.page.ts
> +    return $('.cart_navigation > button');
El selector que enuncias no da como resultado un elemento

2017-10-18 13:57 UTC, Blesfia commented on src/page/AddressStep.page.ts
> +    return $('.cart_navigation > button');
Lo cambiare por [name=processAddress]

2017-10-18 13:58 UTC, Blesfia commented on src/page/BankPayment.page.ts
> +    return $('.cart_navigation > button');
Tienes razón, no existe razón lógica para cambiar # por .

2017-10-18 22:24 UTC, Blesfia commented on src/page/PaymentStep.page.ts
> +    return $('#HOOK_PAYMENT .bankwire');
Si coloco el ID asegurar mas la mantenibilidad de este selector por si se agrega otro elemento que contenga la misma clase

2017-10-18 22:33 UTC, Blesfia commented on src/page/ShippingStep.page.ts
> +    return $('.cart_navigation > button');
Listo, corregido

2017-10-19 11:25 UTC, aperdomob approved these changes

2017-10-19 19:26 UTC, merged