add test
Blesfia/protractor-workshop-2017 pull request #16
Opened 2017-10-19 19:26 UTC by Blesfia

2017-10-21 14:19 UTC, jhenaoz requested changes

2017-10-21 14:19 UTC, jhenaoz commented on test/BuyTshirt.spec.ts
> +  describe('Abrir la página en el navegador', () => {
mezcla de ingles y español en un mismo proyecto?

2017-10-21 14:19 UTC, jhenaoz commented on test/BuyTshirt.spec.ts
> +    it('', async () => {
falta escribir la informacion de los it
formato Given When Then (Gherkin)

2017-10-21 22:54 UTC, Blesfia commented on test/BuyTshirt.spec.ts
> +  describe('Abrir la página en el navegador', () => {
Pero asi dice el ejercicio que los escriba, solo segui el ejercicio al pie de la letra :(

2017-10-23 13:24 UTC, jhenaoz approved these changes

2017-11-19 14:49 UTC, merged